# Generated by Django 5.0.14 on 2026-03-12 20:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scolaireapp', '0001_initial'),
        ('user', '0004_ecole_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Frais',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frais', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolaireapp.anneescolaires')),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scolaireapp.classes')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.ecole')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.section')),
            ],
            options={
                'verbose_name': 'Frais',
                'verbose_name_plural': 'Frais',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolaireapp.anneescolaires')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.ecole')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolaireapp.eleves')),
                ('frais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.frais')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.section')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
        migrations.CreateModel(
            name='RepartitionFrais',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motif', models.CharField(max_length=50)),
                ('montant', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolaireapp.anneescolaires')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.ecole')),
                ('frais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.frais')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.section')),
            ],
            options={
                'verbose_name': 'RepartitionFrais',
                'verbose_name_plural': 'RepartitionFrais',
            },
        ),
    ]
