# Generated by Django 5.0.14 on 2026-03-14 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('scolaireapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frais',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scolaireapp.options'),
        ),
    ]
