# Generated by Django 5.0.14 on 2026-03-15 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_frais_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frais',
            name='option',
        ),
    ]
