# Generated by Django 5.0.14 on 2026-03-20 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_frais_option'),
        ('scolaireapp', '0003_remove_inscriptions_option'),
        ('user', '0006_utilisateurs_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='annee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scolaireapp.anneescolaires'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='ecole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.ecole'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='eleve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scolaireapp.eleves'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='frais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.repartitionfrais'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.section'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
