# Generated by Django 4.2 on 2025-12-09 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scolaireapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('ponderation', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolaireapp.classes')),
            ],
        ),
        migrations.CreateModel(
            name='Enseignants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noms', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('sexe', models.CharField(max_length=50)),
                ('datenaissance', models.DateField()),
                ('lieunaissance', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=50)),
                ('etatcivil', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ponderations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_obtenu', models.FloatField()),
                ('periode', models.CharField(max_length=50)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolaireapp.anneeacademiques')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.cours')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolaireapp.eleves')),
            ],
        ),
        migrations.CreateModel(
            name='Affectations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolaireapp.anneeacademiques')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.cours')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.enseignants')),
            ],
        ),
    ]
