# Generated by Django 5.0.14 on 2026-03-10 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cours', '0001_initial'),
        ('scolaireapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectations',
            name='annee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolaireapp.anneescolaires'),
        ),
        migrations.AddField(
            model_name='cours',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolaireapp.classes'),
        ),
        migrations.AddField(
            model_name='affectations',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.cours'),
        ),
        migrations.AddField(
            model_name='affectations',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.enseignants'),
        ),
        migrations.AddField(
            model_name='ponderations',
            name='annee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolaireapp.anneescolaires'),
        ),
        migrations.AddField(
            model_name='ponderations',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.cours'),
        ),
        migrations.AddField(
            model_name='ponderations',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolaireapp.eleves'),
        ),
    ]
