# Generated by Django 5.0.14 on 2026-03-10 20:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_alter_ecole_id_alter_section_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleves',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matricule', models.CharField(max_length=50, null=True)),
                ('nom', models.CharField(max_length=50)),
                ('postnom', models.CharField(max_length=50, null=True)),
                ('prenom', models.CharField(max_length=50)),
                ('sexe', models.CharField(max_length=50)),
                ('lieunaissance', models.CharField(max_length=50)),
                ('datenaissance', models.DateField()),
                ('telephone', models.IntegerField()),
                ('adresse', models.TextField()),
                ('photo', models.ImageField(upload_to='eleves')),
            ],
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, null=True)),
                ('adresse', models.CharField(max_length=50)),
                ('telephone', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnneeScolaires',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('annee', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('ecole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.ecole')),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('classe', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('ecole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.ecole')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.section')),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('ecole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.ecole')),
            ],
        ),
        migrations.CreateModel(
            name='Inscriptions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('dateinscription', models.DateField(auto_now=True)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolaireapp.anneescolaires')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolaireapp.classes')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolaireapp.eleves')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scolaireapp.options')),
            ],
        ),
        migrations.AddField(
            model_name='eleves',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolaireapp.parents'),
        ),
    ]
