# Generated by Django 5.0.14 on 2026-03-15 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolaireapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scolaireapp.options'),
        ),
    ]
