# Generated by Django 5.0.14 on 2026-03-15 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scolaireapp', '0002_classes_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscriptions',
            name='option',
        ),
    ]
