# Generated by Django 4.2 on 2026-02-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecole',
            name='telephone',
            field=models.IntegerField(),
        ),
    ]
