# Generated by Django 5.0.14 on 2026-03-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_ecole_id_alter_section_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
