# Generated by Django 5.0.14 on 2026-03-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_section_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateurs',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
